### ISSUE TITLE
Can't run 2.2.0

### ISSUE THREAD

**Issue by lxsli** [rm-hull/nvd-clojure#128]
Can't run 2.2.0, 2.1.0 works fine. Lein version 2.9.7.

```
WARNING: reader macro ^ is deprecated; use meta instead
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol (json.clj:23)
	at clojure.lang.Compiler.eval(Compiler.java:4658)
	at clojure.lang.Compiler.load(Compiler.java:4972)
	at clojure.lang.RT.loadResourceScript(RT.java:330)
	at clojure.lang.RT.loadResourceScript(RT.java:321)
	at clojure.lang.RT.load(RT.java:399)
	at clojure.lang.RT.load(RT.java:371)
	at clojure.core$load__6449$fn__6458.invoke(core.clj:4171)
	at clojure.core$load__6449.doInvoke(core.clj:4170)
	at clojure.lang.RestFn.invoke(RestFn.java:413)
	at clojure.core$load_one__6379.invoke(core.clj:4007)
	at clojure.core$load_lib__6400.doInvoke(core.clj:4044)
	at clojure.lang.RestFn.applyTo(RestFn.java:147)
	at clojure.core$apply__4370.invoke(core.clj:438)
	at clojure.core$load_libs__6417.doInvoke(core.clj:4070)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply__4370.invoke(core.clj:438)
	at clojure.core$require__6440.doInvoke(core.clj:4138)
	at clojure.lang.RestFn.invoke(RestFn.java:522)
	at nvd.task.check$eval__24$loading__6309__auto____26.invoke(check.clj:23)
	at nvd.task.check$eval__24.invoke(check.clj:23)
	at clojure.lang.Compiler.eval(Compiler.java:4642)
	at clojure.lang.Compiler.eval(Compiler.java:4634)
	at clojure.lang.Compiler.load(Compiler.java:4972)
	at clojure.lang.RT.loadResourceScript(RT.java:330)
	at clojure.lang.RT.loadResourceScript(RT.java:321)
	at clojure.lang.RT.load(RT.java:399)
	at clojure.lang.RT.load(RT.java:371)
	at clojure.core$load__6449$fn__6458.invoke(core.clj:4171)
	at clojure.core$load__6449.doInvoke(core.clj:4170)
	at clojure.lang.RestFn.invoke(RestFn.java:413)
	at clojure.core$load_one__6379.invoke(core.clj:4007)
	at clojure.core$load_lib__6400.doInvoke(core.clj:4044)
	at clojure.lang.RestFn.applyTo(RestFn.java:147)
	at clojure.core$apply__4370.invoke(core.clj:438)
	at clojure.core$load_libs__6417.doInvoke(core.clj:4070)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply__4370.invoke(core.clj:438)
	at clojure.core$require__6440.doInvoke(core.clj:4138)
	at clojure.lang.RestFn.invoke(RestFn.java:413)
	at user$eval__4$fn__7.invoke(103aad1f2e34ebf582fc4e432489001a7982762050221a61266fb0f4d16b67b8-init.clj:1)
	at user$eval__4.invoke(103aad1f2e34ebf582fc4e432489001a7982762050221a61266fb0f4d16b67b8-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:4642)
	at clojure.lang.Compiler.eval(Compiler.java:4634)
	at clojure.lang.Compiler.load(Compiler.java:4972)
	at clojure.lang.Compiler.loadFile(Compiler.java:4939)
	at clojure.main$load_script__7405.invoke(main.clj:213)
	at clojure.main$init_opt__7408.invoke(main.clj:218)
	at clojure.main$initialize__7418.invoke(main.clj:246)
	at clojure.main$null_opt__7446.invoke(main.clj:271)
	at clojure.main$main__7466.doInvoke(main.clj:346)
	at clojure.lang.RestFn.invoke(RestFn.java:426)
	at clojure.lang.Var.invoke(Var.java:363)
	at clojure.lang.AFn.applyToHelper(AFn.java:175)
	at clojure.lang.Var.applyTo(Var.java:476)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
	at clojure.lang.LazySeq.sval(LazySeq.java:47)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.LazySeq.first(LazySeq.java:78)
	at clojure.lang.RT.first(RT.java:549)
	at clojure.core$first__4227.invoke(core.clj:45)
	at clojure.core$ns__6317.doInvoke(core.clj:3912)
	at clojure.lang.RestFn.invoke(RestFn.java:479)
	at clojure.lang.Var.invoke(Var.java:375)
	at clojure.lang.AFn.applyToHelper(AFn.java:190)
	at clojure.lang.Var.applyTo(Var.java:476)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:4504)
	at clojure.lang.Compiler.macroexpand(Compiler.java:4564)
	at clojure.lang.Compiler.eval(Compiler.java:4628)
	... 54 more
Caused by: java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
	at clojure.lang.RT.seqFrom(RT.java:479)
	at clojure.lang.RT.seq(RT.java:442)
	at clojure.lang.RT.first(RT.java:550)
	at clojure.core$first__4227.invoke(core.clj:45)
	at clojure.core$ns__6317$fn__6327.invoke(core.clj:3912)
	at clojure.core$filter__5084$fn__5086.invoke(core.clj:1804)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	... 66 more
Error encountered performing task 'run' with profile(s): 'base,system,provided,dev'
Suppressed exit
```

**Comment by lxsli** [comment]
I said 2.1.0 works fine... but it has debug logging enabled, so it's not ideal

**Comment by vemv** [comment]
Hi, thank you for using nvd-clojure!

Please paste the exact steps that you are using to run `nvd-clojure.`

**Comment by lxsli** [comment]
We use a monorepo. As instructed, I've created a new project in `nvd/`:

```
(defproject ccm.greshamtech.com/worker "local"
  :description "nvd-clojure helper project"
  :dependencies [[nvd-clojure "2.2.0"]])
```

Then I run:

    lein with-profile -user run -m nvd.task.check "" "$(cd ../genesis && lein with-profile -user,-dev classpath)"

(I've actually made a Makefile to generate classpaths and put aliases into the project.clj, but the above is sufficient to reproduce the error)

**Comment by puredanger** [comment]
This is happening while Clojure runtime is loading user.clj - maybe you're accidentally including something on your classpath that you don't expect?

**Comment by vemv** [comment]
Another line that you can research is that googling the following query:

```
reader macro ^ is deprecated; "use meta instead"
```

..shows _very_ old results. Maybe the Clojure version is that old?

You can try the following:

```diff
(defproject ccm.greshamtech.com/worker "local"
  :description "nvd-clojure helper project"
  :dependencies [[nvd-clojure "2.2.0"]
+                [org.clojure/clojure "1.10.3"]])
```

**Comment by lxsli** [comment]
Ah adding a clojure dep did it! Thank you!

**Comment by vemv** [comment]
Cheers. PR welcome for the README.
