### ISSUE TITLE
Running from Clojure CLI gives java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by pmonks** [rm-hull/nvd-clojure#142]
**Steps to reproduce:**
```
$ clojure -J-Dclojure.main.report=stderr -Srepro -Sdeps '{:deps {nvd-clojure/nvd-clojure {:mvn/version "RELEASE"}}}' -M -m nvd.task.check "" ~/.m2/repository/org/clojure/clojure/1.11.1/clojure-1.11.1.jar
```
Note: I was originally trying a longer list of JARs, but the issue can be reproduced with just a single JAR, as shown above.

**Expected result:**
A dependency check report is emitted.

**Actual result:**
```
WARN  Disabling Nexus analyzer - please specify the URL to a Nexus Server
Checking dependencies for stdin...
  using nvd-clojure: 2.6.0 and dependency-check: 7.1.0
WARN  An unexpected error occurred during analysis of '/Users/pmonks/.m2/repository/org/clojure/clojure/1.11.1/clojure-1.11.1.jar' (Sonatype OSS Index Analyzer): 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
ERROR
java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.<init>(DirectoryCache.java:84)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration.create(DirectoryCache.java:328)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.<init>(OssindexClientImpl.java:96)
	at org.owasp.dependencycheck.data.ossindex.OssindexClientFactory.create(OssindexClientFactory.java:122)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.newOssIndexClient(OssIndexAnalyzer.java:227)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:217)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:134)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Encountered errors while analyzing: One or more exceptions occurred during analysis:
	NoSuchMethodError: 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
#error {
 :cause 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
 :via
 [{:type java.lang.NoSuchMethodError
   :message 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
   :at [org.sonatype.ossindex.service.client.cache.DirectoryCache <init> DirectoryCache.java 84]}]
 :trace
 [[org.sonatype.ossindex.service.client.cache.DirectoryCache <init> DirectoryCache.java 84]
  [org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration create DirectoryCache.java 328]
  [org.sonatype.ossindex.service.client.internal.OssindexClientImpl <init> OssindexClientImpl.java 96]
  [org.owasp.dependencycheck.data.ossindex.OssindexClientFactory create OssindexClientFactory.java 122]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer newOssIndexClient OssIndexAnalyzer.java 227]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer requestReports OssIndexAnalyzer.java 217]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer analyzeDependency OssIndexAnalyzer.java 134]
  [org.owasp.dependencycheck.analyzer.AbstractAnalyzer analyze AbstractAnalyzer.java 131]
  [org.owasp.dependencycheck.AnalysisTask call AnalysisTask.java 88]
  [org.owasp.dependencycheck.AnalysisTask call AnalysisTask.java 37]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1136]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 635]
  [java.lang.Thread run Thread.java 833]]}
{:clojure.main/message
 "Execution error (ExceptionInfo) at nvd.task.check/scan-and-analyze$fn (check.clj:58).\norg.owasp.dependencycheck.exception.ExceptionCollection\n",
 :clojure.main/triage
 {:clojure.error/class clojure.lang.ExceptionInfo,
  :clojure.error/line 58,
  :clojure.error/cause
  "org.owasp.dependencycheck.exception.ExceptionCollection",
  :clojure.error/symbol nvd.task.check/scan-and-analyze$fn,
  :clojure.error/source "check.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ExceptionInfo,
    :message "org.owasp.dependencycheck.exception.ExceptionCollection",
    :data {:exceptions [#error {
 :cause "'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'"
 :via
 [{:type java.lang.NoSuchMethodError
   :message "'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'"
   :at [org.sonatype.ossindex.service.client.cache.DirectoryCache <init> "DirectoryCache.java" 84]}]
 :trace
 [[org.sonatype.ossindex.service.client.cache.DirectoryCache <init> "DirectoryCache.java" 84]
  [org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration create "DirectoryCache.java" 328]
  [org.sonatype.ossindex.service.client.internal.OssindexClientImpl <init> "OssindexClientImpl.java" 96]
  [org.owasp.dependencycheck.data.ossindex.OssindexClientFactory create "OssindexClientFactory.java" 122]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer newOssIndexClient "OssIndexAnalyzer.java" 227]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer requestReports "OssIndexAnalyzer.java" 217]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer analyzeDependency "OssIndexAnalyzer.java" 134]
  [org.owasp.dependencycheck.analyzer.AbstractAnalyzer analyze "AbstractAnalyzer.java" 131]
  [org.owasp.dependencycheck.AnalysisTask call "AnalysisTask.java" 88]
  [org.owasp.dependencycheck.AnalysisTask call "AnalysisTask.java" 37]
  [java.util.concurrent.FutureTask run "FutureTask.java" 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1136]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 635]
  [java.lang.Thread run "Thread.java" 833]]}]},
    :at
    [nvd.task.check$scan_and_analyze$fn__709 invoke "check.clj" 58]}],
  :trace
  [[nvd.task.check$scan_and_analyze$fn__709 invoke "check.clj" 58]
   [nvd.task.check$scan_and_analyze invokeStatic "check.clj" 52]
   [nvd.task.check$scan_and_analyze invoke "check.clj" 47]
   [nvd.task.check$impl invokeStatic "check.clj" 90]
   [nvd.task.check$impl invoke "check.clj" 82]
   [nvd.task.check$_main invokeStatic "check.clj" 147]
   [nvd.task.check$_main doInvoke "check.clj" 98]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "org.owasp.dependencycheck.exception.ExceptionCollection",
  :data {:exceptions [#error {
 :cause "'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'"
 :via
 [{:type java.lang.NoSuchMethodError
   :message "'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'"
   :at [org.sonatype.ossindex.service.client.cache.DirectoryCache <init> "DirectoryCache.java" 84]}]
 :trace
 [[org.sonatype.ossindex.service.client.cache.DirectoryCache <init> "DirectoryCache.java" 84]
  [org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration create "DirectoryCache.java" 328]
  [org.sonatype.ossindex.service.client.internal.OssindexClientImpl <init> "OssindexClientImpl.java" 96]
  [org.owasp.dependencycheck.data.ossindex.OssindexClientFactory create "OssindexClientFactory.java" 122]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer newOssIndexClient "OssIndexAnalyzer.java" 227]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer requestReports "OssIndexAnalyzer.java" 217]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer analyzeDependency "OssIndexAnalyzer.java" 134]
  [org.owasp.dependencycheck.analyzer.AbstractAnalyzer analyze "AbstractAnalyzer.java" 131]
  [org.owasp.dependencycheck.AnalysisTask call "AnalysisTask.java" 88]
  [org.owasp.dependencycheck.AnalysisTask call "AnalysisTask.java" 37]
  [java.util.concurrent.FutureTask run "FutureTask.java" 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1136]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 635]
  [java.lang.Thread run "Thread.java" 833]]}]}}}

Execution error (ExceptionInfo) at nvd.task.check/scan-and-analyze$fn (check.clj:58).
org.owasp.dependencycheck.exception.ExceptionCollection
```

**Environment:**
```
$ uname -a
Darwin newnes 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
$ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
$ clojure --version
Clojure CLI version 1.11.1.1113
```

**Comment by vemv** [comment]
Hi, thanks for the report!

The provided command works for me as-is.

It's worth noting, we have JDK 17 in our CI which has a comprehensive integration test suite (and is green).

Have you tried running the command in a non-project dir? e.g. anything not having deps.edn at its root.

**Comment by vemv** [comment]
I'll close the issue because I'm pretty certain about what it is.

https://github.com/rm-hull/nvd-clojure/tree/v2.6.0#clojure-cli is pretty clear:

> Please create a separate project consisting exclusively of nvd-clojure/nvd-clojure {:mvn/version "2.5.0"}. Said project can be located inside the targeted repo's Git repository.

Alternatively, you can use the CLI Tool.

**Comment by pmonks** [comment]
Thanks for replying.

> Have you tried running the command in a non-project dir?

Yes, and that works but doesn't meet my needs.  I need to be able to run NVD in a directory where a `deps.edn` is present (since that's used to calculate the classpath to be passed to NVD, albeit in Clojure code not shell), in a JVM that does not have its classpath constructed from that `deps.edn` file (since, as the docs clearly state, NVD is incredibly sensitive to the classpath of the JVM its running in).

> Alternatively, you can use the CLI Tool.

Not really, as they're ill-suited to CI environments where this logic will mostly be running (the requirement to "install" a tool prior to "running" it is problematic in non-persistent environments, and to date I've been unable to find a way to just "run" a tool directly without explicitly installing it first).

I also looked into `:replace-deps` but it only works with CLI Tool invocations, and not other types of Clojure CLI invocation.

Really what all of this investigation demonstrated (to me, at least) is that this is fundamentally a problem with the Clojure CLI, and not anything the NVD project can really do anything about.

**Comment by vemv** [comment]
> I need to be able to run NVD in a directory where a deps.edn is present 

Why? Generally a CI pipeline can do whatever you tell it to. Or you can work around a bash script invoked from your project root dir, which performs a `cd` within it.

Anyway the official example is fairly simple:

```
clojure -J-Dclojure.main.report=stderr -M -m nvd.task.check "" "$(cd <YOUR_PROJECT>; clojure -Spath -A:any:aliases)"
```

It's worth giving it a fair chance.

> "install" a tool prior to "running" it is problematic in non-persistent environments

From what I know, Tools can be cached, just like e.g. Maven artifacts are cached (via their `.m2` dir).

---

Ultimately you can build an "uberjar" of nvd-clojure / its dependencies and run it through vanilla `java`. From our side, we won't do that, as distributing what essentially is a blob isn't quite apt for a security offering.
