### ISSUE TITLE
exception in thread "main" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by ghost** [rm-hull/nvd-clojure#27]
Trying to run `lein nvd check` the example project is resulting in the below exception.

Using lein 2.8.1 

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;, compiling:(/private/var/folders/32/k631300x10xgjqf3gpxgc38r0000gn/T/form-init7686865009871791344.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.createTables(ConnectionFactory.java:321)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:183)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:226)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:196)
        at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:950)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:892)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:871)
        at nvd.task.update_database$_main.invokeStatic(update_database.clj:35)
        at nvd.task.update_database$_main.invoke(update_database.clj:29)
        at user$eval683.invokeStatic(form-init7686865009871791344.clj:1)
        at user$eval683.invoke(form-init7686865009871791344.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7052)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        ... 12 more
Subprocess failed

**Comment by derekslager** [comment]
Looks like an incompatible version of the `commons-io` library is referenced by Leiningen itself. You can work around by just spawning a separate JVM, as below:

```lein trampoline nvd check```

**Comment by rm-hull** [comment]
@derekslager - thanks, I think I will incorporate that tip into the readme. Do you know if there is a way to always spawn a new JVM from within leiningen itself, so this becomes the default? I’ve moved on a bit from the clojure eco-system these days, so if I did know how to do this, I’ve forgotten now!

**Comment by vemv** [comment]
https://github.com/rm-hull/lein-nvd#avoiding-classpath-interference is a complete guide on avoiding `NoSuchMethodError`s, might suffice to consider this issue solved.

I'm pretty sure I saw `org.apache.commons.io.IOUtils.toString(` among other errors while hacking on this project i.e. I'm positive that it fixes it.

wrt `lein trampoline`, it's a nice one, technically it works although perhaps I wouldn't recommend it in face of: https://github.com/technomancy/leiningen/blob/e270102447fb9ca1f33591d39b72b15d06cdc0ef/src/leiningen/trampoline.clj#L50-L52

The https://github.com/rm-hull/lein-nvd#avoiding-classpath-interference approach is cleaner overall, favoring a vanilla Clojure `-main` program over a careful invocation of a Lein plugin.
